### ISSUE TITLE
CSS broken after npm run build

### ISSUE THREAD

**Issue by ddrag23** [itamarack/laratine#1]
### Description
I'm encountering a broken CSS issue after building the project. The padding on the sidebar is not working as expected. I have tested both locally and on the server, and the problem persists in both environments. I haven’t changed any configuration. Could you please let me know if I might have missed something during the build process?

### Steps to Reproduce
Build the project.
Check the sidebar on any page.
Notice that the padding is not applied correctly.
Expected Behavior
The sidebar padding should work properly after the build.

### Actual Behavior
The padding on the sidebar is missing or not working as expected.

### Environment
Tested both locally and on the server.
No configuration changes were made.
Windows : 11 [my local]
Linux : Ubuntu 22 [my server]
php : 8.3
node : 20.11.1
npm : 10.5.1

### Additional Information
Please let me know if there’s anything that might have been overlooked during the build process.

### Screenshot
![image](https://github.com/user-attachments/assets/8c7b4db4-c46a-4987-b27c-547eab3fed79)

**Comment by itamarack** [comment]
Sorry about that. Just give me a few moment, let me try and recreate the issue on my local instance. Its likely an ENV (APP_URL) issue. Just a moment

**Comment by ddrag23** [comment]
> Sorry about that. Just give me a few moment, let me try and recreate the issue on my local instance. Its likely an ENV (APP_URL) issue. Just a moment

Thank you for the clarification. No worries, take your time. I’ll wait for your update.  If there's anything else I can assist with, feel free to let me know.

**Comment by itamarack** [comment]
@ddrag23 so i found the issue and it turns out that for some reason, React.lazy() is messing with Apexcharts. This issue was from the Dashboard Chart components. I have resolved it and merged to master. 

So to fix it you may have to replace the lines const Chart = React.lazy(import('apex-charts')) and replace with import Chart from 'react-apexcharts'. These imports can be found in both the AreaChart and the Content Chart components.

**Comment by ddrag23** [comment]
> @ddrag23 so i found the issue and it turns out that for some reason, React.lazy() is messing with Apexcharts. This issue was from the Dashboard Chart components. I have resolved it and merged to master.
> 
> So to fix it you may have to replace the lines const Chart = React.lazy(import('apex-charts')) and replace with import Chart from 'react-apexcharts'. These imports can be found in both the AreaChart and the Content Chart components.

thank you very much @itamarack . solved
